<?php
/**
* @file
* Additional configuration necessary to ensure secure environment
*/

/**
* Implements hook_init().
*/

/**
 * Implements hook_menu().
 *
 * Provides a default page to explain what this module does.
 */
function security_update_menu() {
  $items['pdi-secure/security_update'] = array(
    'page callback' => 'security_update_page',
    'access callback' => TRUE,
    'title' => ' Security Update Module',
  );
  return $items;
}

/**
 * Simple page function to explain what custom secure is about.
 */
function security_update_page() {
  $page = array(
    '#type' => 'markup',
    '#markup' => t('Adds some functionality necesssary for security.'),
  );
  return $page;
}

//change the expires headers for to avoid fingereprinting error in vega scan.
function security_update_init() {
  // Change to a different but still "old" value.
  drupal_add_http_header('Expires', 'Sun, 26 June 1978 05:00:00 GMT');
}
