# A sample Gemfile
source "https://rubygems.org"

# gem "rails"
gem 'breakpoint', '~>2.4.1'
gem 'rvm', '~>1.11.3.9'
gem 'sass', '~> 3.3.9'
gem 'compass', '~>1.0.0.alpha.20'
gem 'sass-globbing', '~>1.1.0'
gem 'singularitygs', '~>1.2.0.rc.6'
gem 'toolkit', '~>1.3.8'
